### ISSUE TITLE
Reference policy: discrepancy between `training.sh` and paper

### ISSUE THREAD

**Issue by saparina** [RemiLeblond/SeaRNN-open#3]
I found that parameter `--reference_policy` is missed in all commands from `training.sh`. The default value for `--reference_policy` is `copy-gt`, but in your paper it says you used custom reference policy for NMT, which corresponds to `bleu1-best-suffix` in code, I guess. 
Can you explain this discrepancy, please? Which reference policy should I use for reproducing the NMT results obtained in the paper?

**Comment by RemiLeblond** [comment]
Yes, you're right, the results obtained in the paper were with the bleu1-best-suffix reference policy if I remember correctly.
Note though that the difference is not that big between the two.
You're welcome to update training.sh :-)

**Comment by jalayrac** [comment]
This issue is now closed (resolved by PR #4 )
